import type { ProspectPreviewData } from "@/types/prospect";

export function FooterSection({ data }: { data: ProspectPreviewData }) {
  return (
    <footer className="px-6 py-16 border-t border-zinc-900">
      <div className="max-w-5xl mx-auto">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-12">
          <div className="md:col-span-1">
            {data.logoUrl ? (
              <img
                src={data.logoUrl}
                alt={data.businessName}
                className="h-8 w-auto object-contain max-w-[160px] mb-3 brightness-0 invert opacity-70"
              />
            ) : (
              <div className="font-bold text-xl text-zinc-100 mb-3">
                {data.businessName}
              </div>
            )}
            <p className="text-sm text-zinc-500 max-w-xs leading-relaxed">
              {data.footerTagline ??
                `Professional ${data.category.toLowerCase()} services in ${data.location}. Licensed, insured, and trusted.`}
            </p>
          </div>

          <div>
            <h4 className="text-sm font-semibold text-zinc-100 mb-4">
              Services
            </h4>
            <ul className="space-y-3">
              {data.services.slice(0, 5).map((service) => (
                <li key={service.name}>
                  <a
                    href="#services"
                    className="text-sm text-zinc-500 hover:text-zinc-300 transition-colors"
                  >
                    {service.name}
                  </a>
                </li>
              ))}
            </ul>
          </div>

          <div>
            <h4 className="text-sm font-semibold text-zinc-100 mb-4">
              Contact
            </h4>
            <ul className="space-y-3">
              {data.phone && (
                <li>
                  <a
                    href={`tel:${data.phone}`}
                    className="text-sm text-zinc-500 hover:text-zinc-300 transition-colors"
                  >
                    {data.phone}
                  </a>
                </li>
              )}
              {data.email && (
                <li>
                  <a
                    href={`mailto:${data.email}`}
                    className="text-sm text-zinc-500 hover:text-zinc-300 transition-colors"
                  >
                    {data.email}
                  </a>
                </li>
              )}
              {data.location && (
                <li className="text-sm text-zinc-500">{data.location}</li>
              )}
            </ul>
          </div>
        </div>

        <div className="pt-8 border-t border-zinc-900 flex flex-col md:flex-row items-center justify-between gap-4">
          <p className="text-sm text-zinc-600">
            &copy; {new Date().getFullYear()} {data.businessName}. All rights
            reserved.
          </p>
          <p className="text-xs text-zinc-700">
            Preview generated by{" "}
            <a
              href="https://azlabs.ai"
              target="_blank"
              rel="noopener noreferrer"
              className="hover:text-zinc-500 transition-colors"
            >
              AZ Labs
            </a>
          </p>
        </div>
      </div>
    </footer>
  );
}
